export const resultGuideDefinitions = {
  male: [
    { key: "neck", marker: "circumference", label: "Neck", instruction: "Neck is measured around the base of the neck where the collar sits.", type: "horizontal", x1: 43, x2: 57, y: 45 },
    { key: "chest", marker: "circumference", label: "Chest", instruction: "Chest is measured around the fullest chest, with the tape level across the back.", type: "horizontal", x1: 29, x2: 71, y: 65 },
    { key: "stomach", marker: "circumference", label: "Stomach", instruction: "Stomach is measured around the belly line, usually slightly above the trouser waist.", type: "horizontal", x1: 35, x2: 65, y: 86 },
    { key: "shoulder", marker: "width", label: "Shoulder", instruction: "Shoulder is measured across the back from one shoulder point to the other.", type: "horizontal", x1: 28, x2: 72, y: 48 },
    { key: "armhole", label: "Armhole", instruction: "Armhole is measured around the arm opening from shoulder, underarm, and back up.", type: "curve", cx: 28, cy: 63 },
    { key: "sleeve", label: "Sleeve length", instruction: "Sleeve length is measured from the shoulder point where the sleeve seam starts down to the wrist.", type: "diagonal", x1: 29, y1: 49, x2: 22, y2: 109 },
    { key: "bicep", marker: "circumference", label: "Round sleeve", instruction: "Round sleeve is measured around the fullest part of the upper arm.", type: "horizontal", x1: 21, x2: 31, y: 78 },
    { key: "wrist", marker: "circumference", label: "Cuff / wrist", instruction: "Cuff or wrist is measured around the wrist or desired cuff opening.", type: "horizontal", x1: 21, x2: 29, y: 108 },
    { key: "topLength", label: "Top length", instruction: "Top length is measured from the shoulder near the neck down to the hip or seat line.", type: "vertical", x: 73, y1: 46, y2: 116 },
    { key: "waist", marker: "circumference", label: "Waist", instruction: "Waist is measured around the waistband position where the trouser will sit.", type: "horizontal", x1: 33, x2: 67, y: 104 },
    { key: "seat", marker: "circumference", label: "Seat", instruction: "Seat is measured around the fullest part of the hip or seat.", type: "horizontal", x1: 31, x2: 69, y: 116 },
    { key: "trouserLength", label: "Outseam", instruction: "Outseam is measured from the trouser waistband down the outside leg to the ankle.", type: "vertical", x: 72, y1: 104, y2: 190 },
    { key: "inseam", label: "Inseam", instruction: "Inseam is measured from crotch down the inside leg to the ankle.", type: "vertical", x: 52, y1: 118, y2: 190 },
    { key: "rise", label: "Rise", instruction: "Rise is measured from waistband down to crotch depth.", type: "vertical", x: 45, y1: 104, y2: 117 },
    { key: "thigh", marker: "circumference", label: "Thigh", instruction: "Thigh is measured around the fullest part of the upper thigh.", type: "horizontal", x1: 35, x2: 51, y: 128 },
    { key: "knee", marker: "circumference", label: "Knee", instruction: "Knee is measured around the knee joint.", type: "horizontal", x1: 33, x2: 46, y: 144 },
    { key: "ankle", marker: "circumference", label: "Bottom / ankle", instruction: "Bottom or ankle is measured at the trouser bottom opening.", type: "horizontal", x1: 32, x2: 42, y: 187 },
  ],
  female: [
    { key: "bust", marker: "circumference", label: "Bust", instruction: "Bust is measured around the fullest bust, with the tape level across the back.", type: "horizontal", x1: 32, x2: 68, y: 69 },
    { key: "underbust", marker: "circumference", label: "Underbust", instruction: "Underbust is measured around the ribcage directly below the bust.", type: "horizontal", x1: 34, x2: 66, y: 76 },
    { key: "waist", marker: "circumference", label: "Waist", instruction: "Waist is measured around the natural waist, the narrowest part of the torso.", type: "horizontal", x1: 36, x2: 64, y: 90 },
    { key: "shoulder", marker: "width", label: "Shoulder", instruction: "Shoulder is measured across the back from one shoulder point to the other.", type: "horizontal", x1: 31, x2: 69, y: 49 },
    { key: "bustPoint", label: "Bust point", instruction: "Bust point is measured from shoulder near the neck down to the bust apex.", type: "vertical", x: 43, y1: 49, y2: 68 },
    { key: "bustSpan", marker: "width", label: "Bust span", instruction: "Bust span is measured from one bust apex to the other.", type: "horizontal", x1: 41, x2: 59, y: 68 },
    { key: "frontLength", label: "Front bodice length", instruction: "Front bodice length is measured from shoulder through bust point down to the waist.", type: "vertical", x: 70, y1: 49, y2: 90 },
    { key: "backLength", label: "Back bodice length", instruction: "Back bodice length is measured from back neck down to the natural waist.", type: "vertical", x: 33, y1: 47, y2: 90 },
    { key: "armhole", label: "Armhole", instruction: "Armhole is measured around the arm opening from shoulder, underarm, and back up.", type: "curve", cx: 30, cy: 65 },
    { key: "sleeve", label: "Sleeve length", instruction: "Sleeve length is measured from the shoulder point where the sleeve seam starts down to the wrist.", type: "diagonal", x1: 31, y1: 51, x2: 20, y2: 108 },
    { key: "bicep", marker: "circumference", label: "Round sleeve", instruction: "Round sleeve is measured around the fullest part of the upper arm.", type: "horizontal", x1: 20, x2: 31, y: 79 },
    { key: "topLength", label: "Blouse/top length", instruction: "Blouse or top length is measured from shoulder down to the high hip line.", type: "vertical", x: 72, y1: 49, y2: 105 },
    { key: "waistLower", marker: "circumference", label: "Waist band", instruction: "Waist band is measured around the chosen skirt, trouser, or gown waistband line, usually just below the navel.", type: "horizontal", x1: 35, x2: 65, y: 98 },
    { key: "highHip", marker: "circumference", label: "High hip", instruction: "High hip is measured around the upper hip right below the waistband.", type: "horizontal", x1: 34, x2: 66, y: 105 },
    { key: "hip", marker: "circumference", label: "Full hip", instruction: "Full hip is measured around the broadest point of the hip just below the high hip.", type: "horizontal", x1: 31, x2: 69, y: 116 },
    { key: "waistToHip", label: "Waist to hip", instruction: "Waist to hip is the vertical drop from the natural waist down to the high hip line.", type: "vertical", x: 38, y1: 90, y2: 105 },
    { key: "lowerLength", label: "Skirt/trouser length", instruction: "Skirt or trouser length is measured from the natural waist down to the ankle.", type: "vertical", x: 72, y1: 90, y2: 191 },
    { key: "rise", label: "Rise", instruction: "Rise is measured from the natural waist down to crotch depth for trousers.", type: "vertical", x: 50, y1: 90, y2: 121 },
    { key: "inseam", label: "Inseam", instruction: "Inseam is measured from crotch down the inside leg to the ankle.", type: "vertical", x: 52, y1: 121, y2: 191 },
    { key: "thigh", marker: "circumference", label: "Thigh", instruction: "Thigh is measured around the fullest part of the upper thigh.", type: "horizontal", x1: 35, x2: 51, y: 128 },
    { key: "knee", marker: "circumference", label: "Knee", instruction: "Knee is measured around the knee joint.", type: "horizontal", x1: 34, x2: 46, y: 143 },
    { key: "ankle", marker: "circumference", label: "Ankle / hem", instruction: "Ankle or hem is measured at the trouser ankle or skirt hem opening.", type: "horizontal", x1: 35, x2: 45, y: 186 },
  ],
};
